#!/bin/false

## by using this file
## you help to enforce a common interface

APP_DIR_NAME="${APP_DIR_NAME:-apps}"
APP_ENV_AUTO="${APP_ENV_AUTO:-.env.auto}"
APP_PREFIX="${APP_PREFIX:-nirvai}"
CERTS_DIR_HOST="${CERTS_DIR_HOST:-/etc/ssl/certs}"
CONFIG_DIR_NAME="${CONFIG_DIR_NAME:-configs}"
IAC_DIR_NAME="${IAC_DIR_NAME:-iac}"
IAC_TARGET="${IAC_TARGET:-validation}"
JAIL_DIR_NAME="${JAIL_DIR_NAME:-secrets}"
MAD_HOSTNAME="${MAD_HOSTNAME:-mad.nirv.ai}"
MESH_HOSTNAME="${MESH_HOSTNAME:-mesh.nirv.ai}"
NIRV_SCRIPT_DEBUG="${NIRV_SCRIPT_DEBUG:-0}"
PROJECT_HOSTNAME="${PROJECT_HOSTNAME:-dev.nirv.ai}"
REPO_DIR_NAME="${REPO_DIR_NAME:-core}"

CONFIGS_DIR="${SCRIPTS_DIR_PARENT}/${CONFIG_DIR_NAME}"
JAIL="${SCRIPTS_DIR_PARENT}/${JAIL_DIR_NAME}"
REPO_DIR="${SCRIPTS_DIR_PARENT}/${REPO_DIR_NAME}"
APP_IAC_PATH="${SCRIPTS_DIR_PARENT}/${REPO_DIR_NAME}/${IAC_DIR_NAME}/${IAC_TARGET}"

APPS_DIR="${REPO_DIR}/${APP_DIR_NAME}"
CFSSL_DIR="${CFSSL_DIR:-$CONFIGS_DIR/cfssl}"
